version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android

    steps:
      - checkout

      - run:
          name: get google-services.json
          command: wget https://drive.google.com/u/0/uc?id=1hbHr0LqvRh7diB_eIVo10rMblkWCGF4p -O google-services.json

      - run:
          name: move google-services.json
          command: mv google-services.json ~/project/app

      - run:
          name: chmod permissions
          command: chmod +x ./gradlew

      - run:
          name: debug apk build
          command: ./gradlew assembleDebug

      - store_artifacts:
          path: ~/project/app/build/outputs/apk/debug
          destination: artifact-file
